import os
import uuid
import glob
import json
import tempfile
import threading
import time
from urllib.parse import urlparse
from flask import Flask, request, jsonify, send_file, render_template
import yt_dlp

app = Flask(__name__)
DOWNLOAD_DIR = "/tmp/downloads" if os.environ.get("VERCEL") else os.path.join(os.path.dirname(__file__), "downloads")
os.makedirs(DOWNLOAD_DIR, exist_ok=True)

jobs = {}


def get_cookie_opts(cookies_data, url=None):
    """
    Returns a tuple of (opts_dict, temp_file_path).
    If a temporary file is created, its path is returned so it can be cleaned up later.
    """
    if not cookies_data:
        return {}, None
    
    mode = cookies_data.get("mode", "none")
    if mode == "browser":
        browser = cookies_data.get("browser", "").lower().strip()
        if browser:
            return {"cookiesfrombrowser": (browser,)}, None
    elif mode == "local_file":
        filename = cookies_data.get("filename", "").strip()
        if filename:
            safe_name = os.path.basename(filename)
            file_path = os.path.join(os.path.dirname(__file__), safe_name)
            if os.path.exists(file_path):
                if os.environ.get("VERCEL"):
                    # Copy to writeable /tmp to prevent Vercel read-only filesystem write errors
                    import shutil
                    tmp_path = os.path.join("/tmp", safe_name)
                    try:
                        shutil.copy2(file_path, tmp_path)
                        return {"cookiefile": tmp_path}, tmp_path
                    except Exception:
                        pass
                return {"cookiefile": file_path}, None
            else:
                raise FileNotFoundError(f"Local cookie file {safe_name} not found")
    elif mode == "text":
        cookie_text = cookies_data.get("text", "").strip()
        if cookie_text:
            if cookie_text.startswith("# Netscape") or "\t" in cookie_text:
                netscape_text = cookie_text
            else:
                # Convert raw Cookie header to Netscape format scoped to the URL's domain
                domain = ".instagram.com"
                if url:
                    try:
                        parsed = urlparse(url)
                        netloc = parsed.netloc.split(":")[0]
                        parts = netloc.split(".")
                        if len(parts) >= 2:
                            domain = "." + ".".join(parts[-2:])
                        else:
                            domain = "." + netloc
                    except Exception:
                        pass
                
                lines = [
                    "# Netscape HTTP Cookie File",
                    "# Generated by ReClip from raw header",
                    ""
                ]
                for part in cookie_text.split(";"):
                    part = part.strip()
                    if not part or "=" not in part:
                        continue
                    key, val = part.split("=", 1)
                    key = key.strip()
                    val = val.strip()
                    if key and val:
                        expire = int(time.time() + 31536000)
                        lines.append(f"{domain}\tTRUE\t/\tTRUE\t{expire}\t{key}\t{val}")
                netscape_text = "\n".join(lines)

            fd, path = tempfile.mkstemp(suffix=".txt", prefix="cookies_")
            try:
                with os.fdopen(fd, 'w', encoding='utf-8') as f:
                    f.write(netscape_text)
                return {"cookiefile": path}, path
            except Exception as e:
                try:
                    os.remove(path)
                except OSError:
                    pass
                raise e
    return {}, None


def find_matching_cookie_file(url):
    if not url:
        return None
    try:
        parsed = urlparse(url)
        netloc = parsed.netloc.lower()
        parts = netloc.split(".")
        if len(parts) >= 2:
            base_domain = ".".join(parts[-2:])
        else:
            base_domain = netloc
        
        domain_name = base_domain.replace("www.", "").split(".")[0]
        
        root_dir = os.path.dirname(__file__)
        for name in os.listdir(root_dir):
            if name.endswith(".txt") and os.path.isfile(os.path.join(root_dir, name)):
                if domain_name in name.lower():
                    file_path = os.path.join(root_dir, name)
                    try:
                        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                            first_line = f.readline()
                            if "netscape" in first_line.lower() or "cookie" in first_line.lower():
                                return file_path
                    except Exception:
                        pass
    except Exception:
        pass
    return None


def run_ytdlp_with_fallback(ydl_opts_base, url, cookies_data, download=False):
    """
    Runs a native yt-dlp operation. If mode is "none" and it fails indicating auth needed,
    it attempts to match a local cookie file and retries.
    Returns (info_dict_or_none, used_cookie_file, fallback_activated, error_msg_or_none)
    """
    mode = cookies_data.get("mode", "none") if cookies_data else "none"
    cookie_opts, temp_cookie_file = get_cookie_opts(cookies_data, url)
    
    ydl_opts = {**ydl_opts_base, **cookie_opts}
    
    fallback_activated = False
    used_cookie_file = temp_cookie_file
    
    try:
        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(url, download=download)
                return info, os.path.basename(used_cookie_file) if used_cookie_file else None, False, None
        except Exception as e:
            error_msg = str(e)
            
            needs_auth = (
                "sign in" in error_msg.lower() or
                "login" in error_msg.lower() or
                "empty media response" in error_msg.lower() or
                "confirm you are not a bot" in error_msg.lower() or
                "private video" in error_msg.lower() or
                "http error 403" in error_msg.lower() or
                "members-only" in error_msg.lower()
            )
            
            if mode == "none" and needs_auth:
                local_cookie_path = find_matching_cookie_file(url)
                if local_cookie_path:
                    fallback_activated = True
                    used_cookie_file = local_cookie_path
                    
                    cookie_path_to_use = local_cookie_path
                    temp_cleanup_path = None
                    if os.environ.get("VERCEL"):
                        import shutil
                        temp_cleanup_path = os.path.join("/tmp", os.path.basename(local_cookie_path))
                        try:
                            shutil.copy2(local_cookie_path, temp_cleanup_path)
                            cookie_path_to_use = temp_cleanup_path
                        except Exception:
                            pass
                    
                    ydl_opts_retry = {**ydl_opts_base, "cookiefile": cookie_path_to_use}
                    try:
                        with yt_dlp.YoutubeDL(ydl_opts_retry) as ydl_retry:
                            info_retry = ydl_retry.extract_info(url, download=download)
                            # Keep temp file registered for cleanup if we created it
                            return info_retry, os.path.basename(local_cookie_path), True, None
                    except Exception as e_retry:
                        return None, os.path.basename(local_cookie_path), True, str(e_retry)
                    finally:
                        if temp_cleanup_path:
                            try:
                                os.remove(temp_cleanup_path)
                            except OSError:
                                pass
            return None, os.path.basename(used_cookie_file) if used_cookie_file else None, False, error_msg
    finally:
        if temp_cookie_file:
            try:
                os.remove(temp_cookie_file)
            except OSError:
                pass


def run_download(job_id, url, format_choice, format_id, cookies_data=None):
    try:
        job = jobs[job_id]
        out_template = os.path.join(DOWNLOAD_DIR, f"{job_id}.%(ext)s")

        ydl_opts_base = {
            "noplaylist": True,
            "outtmpl": out_template,
            "quiet": True,
            "no_warnings": True,
        }

        if format_choice == "audio":
            ydl_opts_base["format"] = "bestaudio/best"
            ydl_opts_base["postprocessors"] = [{
                "key": "FFmpegExtractAudio",
                "preferredcodec": "mp3",
                "preferredquality": "192",
            }]
        elif format_id:
            ydl_opts_base["format"] = f"{format_id}+bestaudio/best"
            ydl_opts_base["merge_output_format"] = "mp4"
        else:
            ydl_opts_base["format"] = "bestvideo+bestaudio/best"
            ydl_opts_base["merge_output_format"] = "mp4"

        info, used_cookie, fallback, err = run_ytdlp_with_fallback(ydl_opts_base, url, cookies_data, download=True)

        if err:
            job["status"] = "error"
            job["error"] = err.split("\n")[-1]
            return

        if fallback:
            job["fallback_used"] = used_cookie

        files = glob.glob(os.path.join(DOWNLOAD_DIR, f"{job_id}.*"))
        if not files:
            job["status"] = "error"
            job["error"] = "Download completed but no file was found"
            return

        if format_choice == "audio":
            target = [f for f in files if f.endswith(".mp3")]
            chosen = target[0] if target else files[0]
        else:
            target = [f for f in files if f.endswith(".mp4")]
            chosen = target[0] if target else files[0]

        for f in files:
            if f != chosen:
                try:
                    os.remove(f)
                except OSError:
                    pass

        job["status"] = "done"
        job["file"] = chosen
        ext = os.path.splitext(chosen)[1]
        
        title = info.get("title", "") if info else ""
        if not title:
            title = job.get("title", "").strip()

        if title:
            safe_title = "".join(c for c in title if c not in r'\/:*?"<>|').strip()[:20].strip()
            job["filename"] = f"{safe_title}{ext}" if safe_title else os.path.basename(chosen)
        else:
            job["filename"] = os.path.basename(chosen)
    except Exception as e:
        job["status"] = "error"
        job["error"] = str(e)


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/api/cookie-files")
def list_cookie_files():
    files = []
    root_dir = os.path.dirname(__file__)
    try:
        for name in os.listdir(root_dir):
            if name.endswith(".txt") and os.path.isfile(os.path.join(root_dir, name)):
                file_path = os.path.join(root_dir, name)
                try:
                    with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                        first_line = f.readline()
                        if "netscape" in first_line.lower() or "cookie" in first_line.lower() or "instagram.com" in name:
                            files.append(name)
                except Exception:
                    pass
    except Exception as e:
        return jsonify({"error": str(e)}), 500
    return jsonify({"files": files})


@app.route("/api/info", methods=["POST"])
def get_info():
    data = request.json
    url = data.get("url", "").strip()
    if not url:
        return jsonify({"error": "No URL provided"}), 400

    cookies_data = data.get("cookies")
    ydl_opts_base = {
        "noplaylist": True,
        "quiet": True,
        "no_warnings": True,
    }
    try:
        info, used_cookie, fallback, err = run_ytdlp_with_fallback(ydl_opts_base, url, cookies_data, download=False)
        if err:
            return jsonify({"error": err.split("\n")[-1]}), 400

        # Build quality options — keep best format per resolution
        best_by_height = {}
        for f in info.get("formats", []):
            height = f.get("height")
            if height and f.get("vcodec", "none") != "none":
                tbr = f.get("tbr") or 0
                if height not in best_by_height or tbr > (best_by_height[height].get("tbr") or 0):
                    best_by_height[height] = f

        formats = []
        for height, f in best_by_height.items():
            formats.append({
                "id": f["format_id"],
                "label": f"{height}p",
                "height": height,
            })
        formats.sort(key=lambda x: x["height"], reverse=True)

        res_data = {
            "title": info.get("title", ""),
            "thumbnail": info.get("thumbnail", ""),
            "duration": info.get("duration"),
            "uploader": info.get("uploader", ""),
            "formats": formats,
        }
        if fallback:
            res_data["fallback_used"] = used_cookie
        return jsonify(res_data)
    except Exception as e:
        return jsonify({"error": str(e)}), 400


@app.route("/api/playlist", methods=["POST"])
def get_playlist_info():
    data = request.json
    url = data.get("url", "").strip()
    if not url:
        return jsonify({"error": "No URL provided"}), 400

    cookies_data = data.get("cookies")
    ydl_opts_base = {
        "extract_flat": "in_playlist",
        "quiet": True,
        "no_warnings": True,
    }
    try:
        info, used_cookie, fallback, err = run_ytdlp_with_fallback(ydl_opts_base, url, cookies_data, download=False)
        if err:
            return jsonify({"error": err.split("\n")[-1]}), 400

        entries = info.get("entries", [])
        urls = [entry.get("url") for entry in entries if entry.get("url")]
        res_data = {"urls": urls}
        if fallback:
            res_data["fallback_used"] = used_cookie
        return jsonify(res_data)
    except Exception as e:
        return jsonify({"error": str(e)}), 400


@app.route("/api/download", methods=["POST"])
def start_download():
    data = request.json
    url = data.get("url", "").strip()
    format_choice = data.get("format", "video")
    format_id = data.get("format_id")
    title = data.get("title", "")

    if not url:
        return jsonify({"error": "No URL provided"}), 400

    cookies_data = data.get("cookies")

    job_id = uuid.uuid4().hex[:10]
    jobs[job_id] = {"status": "downloading", "url": url, "title": title}

    thread = threading.Thread(
        target=run_download,
        args=(job_id, url, format_choice, format_id, cookies_data)
    )
    thread.daemon = True
    thread.start()

    return jsonify({"job_id": job_id})


@app.route("/api/status/<job_id>")
def check_status(job_id):
    job = jobs.get(job_id)
    if not job:
        return jsonify({"error": "Job not found"}), 404
    return jsonify({
        "status": job["status"],
        "error": job.get("error"),
        "filename": job.get("filename"),
        "fallback_used": job.get("fallback_used"),
    })


@app.route("/api/file/<job_id>")
def download_file(job_id):
    job = jobs.get(job_id)
    if not job or job["status"] != "done":
        return jsonify({"error": "File not ready"}), 404
    return send_file(job["file"], as_attachment=True, download_name=job["filename"])


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8899))
    host = os.environ.get("HOST", "127.0.0.1")
    app.run(host=host, port=port)
