import os
import shutil
import tempfile
import urllib.request
import zipfile
import subprocess
import yt_dlp
import glob
from urllib.parse import urlparse
from src.config import BASE_DIR, DOWNLOAD_DIR


def ensure_ffmpeg():
    import shutil
    import sys
    import urllib.request
    import zipfile
    
    # 1. Try system-installed ffmpeg
    system_ffmpeg = shutil.which("ffmpeg")
    if system_ffmpeg:
        return system_ffmpeg
        
    # 2. Try imageio-ffmpeg static package
    try:
        import imageio_ffmpeg
        ffmpeg_path = imageio_ffmpeg.get_ffmpeg_exe()
        if ffmpeg_path and os.path.exists(ffmpeg_path):
            # Put imageio-ffmpeg binary folder into PATH so subprocesses can find it
            ffmpeg_dir = os.path.dirname(ffmpeg_path)
            if ffmpeg_dir not in os.environ["PATH"]:
                os.environ["PATH"] = ffmpeg_dir + os.pathsep + os.environ["PATH"]
            return ffmpeg_path
    except ImportError:
        pass
        
    # 3. Fallback to dynamic downloader (for backward compatibility on Linux)
    if not sys.platform.startswith("linux"):
        return None
        
    tmp_bin = "/tmp/bin"
    ffmpeg_path = os.path.join(tmp_bin, "ffmpeg")
    if os.path.exists(ffmpeg_path) and os.access(ffmpeg_path, os.X_OK):
        if tmp_bin not in os.environ["PATH"]:
            os.environ["PATH"] = tmp_bin + os.pathsep + os.environ["PATH"]
        return ffmpeg_path
        
    os.makedirs(tmp_bin, exist_ok=True)
    zip_path = os.path.join(tmp_bin, "ffmpeg.zip")
    url = "https://github.com/ffbinaries/ffbinaries-prebuilt/releases/download/v4.4.1/ffmpeg-4.4.1-linux-64.zip"
    
    try:
        urllib.request.urlretrieve(url, zip_path)
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(tmp_bin)
        if os.path.exists(zip_path):
            os.remove(zip_path)
        os.chmod(ffmpeg_path, 0o755)
        
        if tmp_bin not in os.environ["PATH"]:
            os.environ["PATH"] = tmp_bin + os.pathsep + os.environ["PATH"]
        return ffmpeg_path
    except Exception as e:
        print(f"Error downloading ffmpeg: {e}")
        return None


def get_cookie_opts(cookies_data, url=None):
    """
    Returns a tuple of (opts_dict, temp_file_path).
    If a temporary file is created, its path is returned so it can be cleaned up later.
    """
    if not cookies_data:
        return {}, None
    
    mode = cookies_data.get("mode", "none")
    if mode == "browser":
        browser = cookies_data.get("browser", "").lower().strip()
        if browser:
            return {"cookiesfrombrowser": (browser,)}, None
    elif mode == "local_file":
        filename = cookies_data.get("filename", "").strip()
        if filename:
            safe_name = os.path.basename(filename)
            file_path = os.path.join(BASE_DIR, safe_name)
            if os.path.exists(file_path):
                if os.environ.get("VERCEL"):
                    # Copy to writeable /tmp to prevent Vercel read-only filesystem write errors
                    import shutil
                    tmp_path = os.path.join("/tmp", safe_name)
                    try:
                        shutil.copy2(file_path, tmp_path)
                        return {"cookiefile": tmp_path}, tmp_path
                    except Exception:
                        pass
                return {"cookiefile": file_path}, None
            else:
                raise FileNotFoundError(f"Local cookie file {safe_name} not found")
    elif mode == "text":
        cookie_text = cookies_data.get("text", "").strip()
        if cookie_text:
            if cookie_text.startswith("# Netscape") or "\t" in cookie_text:
                netscape_text = cookie_text
            else:
                # Convert raw Cookie header to Netscape format scoped to the URL's domain
                domain = ".instagram.com"
                if url:
                    try:
                        parsed = urlparse(url)
                        netloc = parsed.netloc.split(":")[0]
                        parts = netloc.split(".")
                        if len(parts) >= 2:
                            domain = "." + ".".join(parts[-2:])
                        else:
                            domain = "." + netloc
                    except Exception:
                        pass
                
                lines = [
                    "# Netscape HTTP Cookie File",
                    "# Generated by Instant Download from raw header",
                    ""
                ]
                for part in cookie_text.split(";"):
                    part = part.strip()
                    if not part or "=" not in part:
                        continue
                    key, val = part.split("=", 1)
                    key = key.strip()
                    val = val.strip()
                    if key and val:
                        expire = int(time.time() + 31536000)
                        lines.append(f"{domain}\tTRUE\t/\tTRUE\t{expire}\t{key}\t{val}")
                netscape_text = "\n".join(lines)

            fd, path = tempfile.mkstemp(suffix=".txt", prefix="cookies_")
            try:
                with os.fdopen(fd, 'w', encoding='utf-8') as f:
                    f.write(netscape_text)
                return {"cookiefile": path}, path
            except Exception as e:
                try:
                    os.remove(path)
                except OSError:
                    pass
                raise e
    return {}, None

def find_matching_cookie_file(url):
    if not url:
        return None
    try:
        parsed = urlparse(url)
        netloc = parsed.netloc.lower()
        parts = netloc.split(".")
        if len(parts) >= 2:
            base_domain = ".".join(parts[-2:])
        else:
            base_domain = netloc
        
        domain_name = base_domain.replace("www.", "").split(".")[0]
        
        root_dir = BASE_DIR
        for name in os.listdir(root_dir):
            if name.endswith(".txt") and os.path.isfile(os.path.join(root_dir, name)):
                if domain_name in name.lower():
                    file_path = os.path.join(root_dir, name)
                    try:
                        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                            first_line = f.readline()
                            if "netscape" in first_line.lower() or "cookie" in first_line.lower():
                                return file_path
                    except Exception:
                        pass
    except Exception:
        pass
    return None

def run_ytdlp_with_fallback(ydl_opts_base, url, cookies_data, download=False):
    """
    Runs a native yt-dlp operation. If mode is "none" and it fails indicating auth needed,
    it attempts to match a local cookie file and retries.
    Returns (info_dict_or_none, used_cookie_file, fallback_activated, error_msg_or_none)
    """
    ffmpeg_bin = ensure_ffmpeg()
    if ffmpeg_bin:
        ydl_opts_base = {**ydl_opts_base, "ffmpeg_location": ffmpeg_bin}
        
    mode = cookies_data.get("mode", "none") if cookies_data else "none"
    cookie_opts, temp_cookie_file = get_cookie_opts(cookies_data, url)
    
    ydl_opts = {**ydl_opts_base, **cookie_opts, "logger": SilentLogger()}
    
    fallback_activated = False
    used_cookie_file = temp_cookie_file
    
    try:
        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(url, download=download)
                return info, os.path.basename(used_cookie_file) if used_cookie_file else None, False, None
        except Exception as e:
            error_msg = str(e)
            
            needs_auth = (
                "sign in" in error_msg.lower() or
                "login" in error_msg.lower() or
                "empty media response" in error_msg.lower() or
                "confirm you are not a bot" in error_msg.lower() or
                "private video" in error_msg.lower() or
                "private" in error_msg.lower() or
                "unreachable" in error_msg.lower() or
                "http error 403" in error_msg.lower() or
                "members-only" in error_msg.lower()
            )
            
            if mode == "none" and needs_auth:
                local_cookie_path = find_matching_cookie_file(url)
                if local_cookie_path:
                    fallback_activated = True
                    used_cookie_file = local_cookie_path
                    
                    cookie_path_to_use = local_cookie_path
                    temp_cleanup_path = None
                    if os.environ.get("VERCEL"):
                        import shutil
                        temp_cleanup_path = os.path.join("/tmp", os.path.basename(local_cookie_path))
                        try:
                            shutil.copy2(local_cookie_path, temp_cleanup_path)
                            cookie_path_to_use = temp_cleanup_path
                        except Exception:
                            pass
                    
                    ydl_opts_retry = {**ydl_opts_base, "cookiefile": cookie_path_to_use, "logger": SilentLogger()}
                    try:
                        with yt_dlp.YoutubeDL(ydl_opts_retry) as ydl_retry:
                            info_retry = ydl_retry.extract_info(url, download=download)
                            # Keep temp file registered for cleanup if we created it
                            return info_retry, os.path.basename(local_cookie_path), True, None
                    except Exception as e_retry:
                        return None, os.path.basename(local_cookie_path), True, str(e_retry)
                    finally:
                        if temp_cleanup_path:
                            try:
                                os.remove(temp_cleanup_path)
                            except OSError:
                                pass
            return None, os.path.basename(used_cookie_file) if used_cookie_file else None, False, error_msg
    finally:
        if temp_cookie_file:
            try:
                os.remove(temp_cookie_file)
            except OSError:
                pass

def needs_transcoding(input_path):
    import subprocess
    import shutil
    ffmpeg_bin = ensure_ffmpeg()
    if not ffmpeg_bin:
        return False
        
    cmd = [ffmpeg_bin, "-i", input_path]
    try:
        result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, timeout=5)
        stderr = result.stderr.lower()
        
        has_video = "video:" in stderr
        is_h264 = "video: h264" in stderr or "video: avc" in stderr
        
        if has_video and not is_h264:
            return True
            
        has_audio = "audio:" in stderr
        is_compatible_audio = "audio: aac" in stderr or "audio: mp3" in stderr or "audio: mp4a" in stderr
        if has_audio and not is_compatible_audio:
            return True
            
        return False
    except Exception:
        return True

def convert_to_ios_compatible_mp4(input_path):
    import subprocess
    ffmpeg_bin = ensure_ffmpeg()
    if not ffmpeg_bin:
        return input_path

    _, ext = os.path.splitext(input_path)
    if ext.lower() not in [".mp4", ".mov", ".m4v", ".webm", ".mkv", ".3gp", ".avi"]:
        return input_path

    target_path = os.path.splitext(input_path)[0] + ".mp4"
    temp_output = input_path + ".ios.mp4"

    if not needs_transcoding(input_path):
        # File is already H.264/AAC — just run a fast stream-copy to add faststart moov atom
        cmd = [
            ffmpeg_bin, "-y",
            "-i", input_path,
            "-c", "copy",
            "-movflags", "+faststart",
            temp_output
        ]
    else:
        # Full transcode to H.264/AAC with faststart
        cmd = [
            ffmpeg_bin, "-y",
            "-i", input_path,
            "-c:v", "libx264",
            "-preset", "ultrafast",
            "-crf", "23",
            "-pix_fmt", "yuv420p",
            "-profile:v", "high",
            "-level", "4.0",
            "-c:a", "aac",
            "-strict", "experimental",
            "-movflags", "+faststart",
            temp_output
        ]

    try:
        subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, check=True)
        if os.path.exists(temp_output) and os.path.getsize(temp_output) > 0:
            try:
                os.remove(input_path)
            except OSError:
                pass
            if os.path.exists(target_path) and target_path != temp_output:
                try:
                    os.remove(target_path)
                except OSError:
                    pass
            os.rename(temp_output, target_path)
            return target_path
    except Exception:
        if os.path.exists(temp_output):
            try:
                os.remove(temp_output)
            except OSError:
                pass
    return input_path


IMAGE_EXTENSIONS = {"jpg", "jpeg", "webp", "png", "gif", "avif", "heic"}

class SilentLogger:
    def debug(self, msg): pass
    def warning(self, msg): pass
    def error(self, msg): pass

def detect_media_type(info):
    if not info:
        return "video"
    entries = info.get("entries") if info.get("_type") == "playlist" or "entries" in info else None
    items = entries if entries else [info]
    has_video = False
    has_audio = False
    all_images = True
    for item in items:
        if not item: continue
        is_item_image = False
        formats = item.get("formats", [])
        if formats:
            for fmt in formats:
                ext = (fmt.get("ext") or "").lower()
                vcodec = (fmt.get("vcodec") or "none").lower()
                acodec = (fmt.get("acodec") or "none").lower()
                if ext in IMAGE_EXTENSIONS: is_item_image = True
                if vcodec != "none":
                    has_video = True
                    all_images = False
                if acodec != "none": has_audio = True
        else:
            ext = (item.get("ext") or "").lower()
            if ext in IMAGE_EXTENSIONS: 
                is_item_image = True
            elif item.get("url") is None and item.get("thumbnail"):
                is_item_image = True
            else: 
                all_images = False
    if all_images and not has_video: return "image"
    if not has_video and has_audio: return "audio_only"
    return "video"
